#  ________  ___  ___  ___  ___       ________                 ________  ___       ___  ___  ________
#|\   ____\|\  \|\  \|\  \|\  \     |\   ___ \               |\   __  \|\  \     |\  \|\  \|\   ____\
#\ \  \___|\ \  \\\  \ \  \ \  \    \ \  \_|\ \  ____________\ \  \|\  \ \  \    \ \  \\\  \ \  \___|_
# \ \  \  __\ \  \\\  \ \  \ \  \    \ \  \ \\ \|\____________\ \   ____\ \  \    \ \  \\\  \ \_____  \
#  \ \  \|\  \ \  \\\  \ \  \ \  \____\ \  \_\\ \|____________|\ \  \___|\ \  \____\ \  \\\  \|____|\  \
#   \ \_______\ \_______\ \__\ \_______\ \_______\              \ \__\    \ \_______\ \_______\____\_\  \
#    \|_______|\|_______|\|__|\|_______|\|_______|               \|__|     \|_______|\|_______|\_________\
#                                                                                             \|_________|

# 配置版本
version: "1.0"


# 公会命令
admin-command: guildadmin
guild-command: guild

# 暂时仅支持中文
default-language: zh_CN.yml

# 整数范围(0 - 2,147,483,647)
create-guild-money: 10000

# 开启公会战战争时间 单位 秒
start-guild-war-time: 10

# 发送公会战冷却时间 单位 秒
guild-war-cd-time: 60

# 公会战对战时间 单位 秒
battle-against-time: 60

# 职位划分
post:
  - {
    name: "会长", # 职位名称
    level: 1 # 职位等级 等级越低职位越高
  }
  - {
    name: "副会长",
    level: 2
  }
  - {
    name: "元老",
    level: 3
  }
  - {
    name: "精英",
    level: 4
  }
  - {
    name: "会员",
    level: 5
  }

# 公会等级配置 needContribute 需要的贡献值 allowWarehouses 允许使用的仓库类型 count 公会总人数限制
guildLevel:
  {
    "1": { "needContribute": 100,"allowWarehouses": [ "Hopper" ],"count": 10 },
    "2": { "needContribute": 500,"allowWarehouses": [ "Hopper" ],"count": 15 },
    "3": { "needContribute": 1000,"allowWarehouses": [ "Hopper" ],"count": 16 },
    "4": { "needContribute": 1500,"allowWarehouses": [ "Hopper" ],"count": 17 },
    "5": { "needContribute": 2000,"allowWarehouses": [ "Hopper" ],"count": 18 },
    "6": { "needContribute": 3000,"allowWarehouses": [ "Hopper","Chest","Double Chest" ],"count": 19 }
  }
