# 公会GUi配置

# 配置文件版本
version: "1.0"

message-title: "消息窗口"
message-window-back: "返回上级"
message-window-close: "关闭"
message-window-back-img: "textures/ui/Friend1.png"

confirm-window-title: "确认提示"
confirm-guild-war-window-title: "公会宣战书"
confirm-join-guild-true: "确认加入公会"
confirm-join-guild-false: "取消加入公会"
confirm-join-guild-info: "公会名称: {guildName} \n 公会等级: {level} \n 公会简介: {description}"
confirm-remove-member-info: "您确要把玩家 {playerName} 踢出公会吗?"
confirm-kick-player: "确认踢出"
confirm-kick-player-cancel: "取消踢出"
confirm-player-join: "您确认让 {playerName} 进入公会吗?"
confirm-accept-join: "同意加入"
confirm-cancel-join: "拒绝加入"
confirm-unload-product-tips: "您确认下架 {itemName} 商品吗?"
confirm-unload-product: "确认下架"
confirm-unload-product-cancel: "取消下架"
confirm-buy-product-tips: "您确认需要购买 {itemName} 商品吗?"
confirm-buy-product: "确认购买"
confirm-buy-product-cancel: "取消购买"
member-quit-guild-tips: "您确定要退出 {guildName} 公会吗?"
confirm-quit-guild: "确认退出"
confirm-quit-guild-cancel: "取消退出"
dissolve-guild-tips: "您确定要解散 {guildName} 公会吗?"
confirm-dissolve-guild: "确认解散"
confirm-dissolve-guild-cancel: "取消解散"
confirm-accept-war: "接收宣战"
confirm-cancel-war: "拒绝宣战"


guild-title: "公会菜单"
guild-create: "创建公会"
guild-create-img: "textures/ui/anvil_icon.png"
guild-view: "我的公会"
guild-view-img: "textures/ui/anvil_icon.png"
guild-manage: "管理公会"
guild-manage-img: "textures/ui/anvil_icon.png"
guild-join: "加入公会"
guild-join-img: "textures/ui/color_plus.png"
guild-Money-Ranking: "公会贡献榜"
guild-Money-Ranking-img: "textures/items/sign_birch.png"
guild-level-Ranking: "公会等级榜"
guild-level-Ranking-img: "textures/items/sign_acacia.png"
guild-war-victory-ranking: "公会战排行榜"
guild-war-victory-ranking-img: "textures/items/sign_darkoak.png"

create-guild-title: "创建公会"
guild-list-title: "公会列表"
guild-list-info: "公会名称: {guildName} 等级: {level} 会长: {president}"
guild-contribution-ranking-title: "公会贡献排行"
guild-contribution-ranking-info: " 公会名称: {guildName} 会长: {president} 贡献: {contribute}"
guild-victory-ranking-info: " 公会名称: {guildName} 会长: {president} 胜利: {victory}"
guild-level-ranking-title: "公会等级排行榜"
guild-level-ranking-info: " 公会名称: {guildName} 会长: {president} 等级: {level}"

president-window-title: "{guildName} 管理窗口"
president-manage-member: "管理成员"
president-manage-member-img: "textures/ui/color_plus.png"
president-manage-post: "管理职位"
president-manage-post-img: "textures/ui/color_plus.png"
president-temp-apply-list: "公会申请加入列表"
president-temp-apply-list-img: "textures/ui/color_plus.png"
president-war: "公会战"
president-war-img: "textures/ui/color_plus.png"
president-shop: "管理公会商店"
president-shop-img: "textures/ui/color_plus.png"
president-warehouse: "管理仓库"
president-warehouse-img: "textures/ui/color_plus.png"
president-upgrade: "升级公会"
president-upgrade-img: "textures/ui/color_plus.png"
president-position: "设置公会坐标"
president-position-img: "textures/ui/color_plus.png"
president-info: "编辑公会信息"
president-info-img: "textures/ui/color_plus.png"
president-dissolve: "解散公会"
president-dissolve-img: "textures/ui/color_plus.png"

send-war-window-title: "发启公会战"
send-war-guild-list: "宣战的公会"
send-war-declare-war-content: "宣战内容"

guild-admin-window-title: "管理公会配置"
guild-admin-preparing-birthplace: "设置游戏等待点"
guild-admin-preparing-birthplace-img: "textures/ui/color_plus.png"
guild-admin-sparring-points: "设置公会对战点1"
guild-admin-sparring-points-img: "textures/ui/color_plus.png"
guild-admin-sparring-points1: "设置公会对战点2"
guild-admin-sparring-points1-img: "textures/ui/color_plus.png"
guild-admin-gameover-points-img: "textures/ui/color_plus.png"
guild-admin-gameover-points: "设置对战结束点"

president-description-title: "编辑公会信息"
president-description-input: "请输入要设置的公会信息"
president-description-info-title: "公会信息"

manage-post-title: "管理成员职位"
manage-post-member-list: "成员列表"
manage-post-list: "给成员设置的职位列表"


guild-member-list: "公会成员列表"
member-list-format: "玩家:{playerName} 职位:{postName} 贡献:{contribute} \n"
manage-member-list: "管理公会成员"
guild-product-title: "管理商品"
guild-upload-number: "上架商品数量"
guild-upload-product: "上架商品"
guild-upload-product-img: "textures/ui/color_plus.png"
guild-unload-product: "下架商品"
guild-unload-product-img: "textures/ui/color_plus.png"
guild-product-list: "公会商品列表"
guild-product-list-img: "textures/ui/color_plus.png"
upload-product-title: "上架商品"
unload-product-title: "下架商品"
guild-product-format: "商品: {itemName} 数量: {count} 上架人: {playerName} 价格: {price}"

member-window-title: "{guildName} 列表"
member-list: "公会成员列表"
member-list-img: "textures/ui/color_plus.png"
member-warehouse: "公会仓库"
member-warehouse-img: "textures/ui/color_plus.png"
member-shop: "公会商店"
member-shop-img: "textures/ui/color_plus.png"
member-contribute: "公会贡献"
member-contribute-img: "textures/ui/color_plus.png"
member-position: "传送至公会"
member-position-img: "textures/ui/color_plus.png"
member-info: "公会信息"
member-info-img: "textures/ui/color_plus.png"
member-quit-guild: "退出公会"
member-quit-guild-img: "textures/ui/color_plus.png"

contribute-window-title: "贡献窗口"
select-warehouse-title: "选择仓库"
guild-warehouse-allow-type: "允许操作的仓库"
select-warehouse-button: "查看 {warehouse}"

apply-temp-list-title: "玩家申请列表"
manage-warehouse-title: "管理仓库权限"
guild-shop-list-title: "公会商品列表"

