package cn.dawntribe.guild.gui;

/**
 * @author violets007
 * @description: 窗口类型
 * @date: 2022/2/27 1:27 AM
 */
public enum WindowType {

    GUILD_WINDOW,

    CREATE_GUILD_WINDOW,

    MESSAGE_WINDOW,

    PRESIDENT_WINDOW,

    MEMBER_WINDOW,

    CONFIRM_WINDOW,

    MANAGE_MEMBER_LIST_WINDOW,

    MANAGE_APPLY_TEMP_LIST_WINDOW,

    MANAGE_MEMBER_POST_WINDOW,

    MANAGE_WAREHOUSE_WINDOW,

    SELECT_WAREHOUSE_WINDOW,

    CONTRIBUTION_WINDOW,

    EDIT_GUILD_DESCRIPTION,

    GUILD_DESCRIPTION_WINDOW,

    GUILD_PRODUCT_LIST_WINDOW,

    MANAGE_PRODUCT_WINDOW,

    UPLOAD_PRODUCT_WINDOW,

    UNLOAD_PRODUCT_WINDOW,

    PRESIDENT_UNLOAD_PRODUCT_WINDOW,

    GUILD_MEMBER_LIST_WINDOW,

    GUILD_LIST_WINDOW,

    GUILD_CONTRIBUTION_RANKING_WINDOW,

    GUILD_LEVEL_RANKING_WINDOW,

    GUILD_VICTORY_RANKING_WINDOW,

    GUILD_ADMIN_WINDOW,

    SEND_GUILD_WAR_WINDOW
}
